Added ServiceArea service
stevensblueprint/orservice pull request #25
Opened 2024-12-11 21:12 UTC by vinrran

Issue #18

2024-12-12 16:14 UTC, miguel-merlin requested changes

2024-12-12 16:14 UTC, miguel-merlin commented on src/main/java/com/sarapis/orservice/controller/ServiceAreaController.java
> +package com.sarapis.orservice.controller;
Can you remove the `.DS_Store`. These are binary files autogenerated by your OS.

2024-12-12 16:14 UTC, miguel-merlin commented on src/main/java/com/sarapis/orservice/controller/ServiceAreaController.java
> +    public ServiceAreaController(ServiceAreaService serviceAreaService) { //stack overflow the dependency injection paste error and then @autowire
Delete the stack overflow comment

2024-12-12 16:14 UTC, miguel-merlin commented on src/main/java/com/sarapis/orservice/controller/ServiceAreaController.java
> +        List<ServiceAreaDTO> serviceAreaDTOs = this.serviceAreaService.getAllServiceAreas();
You don't need to use `this` when calling the `serviceAreaService` as you already set the attribute in the Constructor of the class. Please change it to `serviceAreaService` instead

2024-12-12 16:14 UTC, miguel-merlin commented on src/main/java/com/sarapis/orservice/controller/ServiceAreaController.java
> +        List<ServiceAreaDTO> serviceAreaDTOs = this.serviceAreaService.getAllServiceAreas();
Same comment for every other usage of `serviceAreaService`

2024-12-12 16:48 UTC, vinrran commented
@miguel-merlin I'm not entirely sure, but most likely the error was resolved after I completed the `ServiceAreaServiceImpl.java` file. 

<img width="945" alt="Screenshot 2024-12-12 at 11 48 04 AM" src="https://github.com/user-attachments/assets/4485f74e-dc7c-43c8-82ce-4d0372fb0292" />

This is a screenshot after I comment out everything in the `ServiceAreaServiceImpl.java` file.

2024-12-14 16:44 UTC, miguel-merlin commented
@vinrran Thanks for the clarification!

2024-12-14 16:45 UTC, miguel-merlin approved these changes
lgtm! NIce job!

2024-12-14 16:45 UTC, merged