Feature/pipeline
stevensblueprint/orservice pull request #8
Opened 2024-11-21 06:26 UTC by miguel-merlin

## Description
Added needed artifacts to enable CI/CD pipeline for Sarapis project

2024-11-21 06:32 UTC, miguel-merlin commented
@ezrizhu I added the Dockerfile, docker-compose and gh workflows to enable the Sarapis pipeline

2024-11-21 19:21 UTC, ezrizhu commented on .github/workflows/build.yaml
why are we running mvn install after docker-compose? are the two dependents of eachother?

2024-11-21 19:44 UTC, miguel-merlin commented on .github/workflows/build.yaml
I created this action to verify that the `pull request` and `push` to main builds. In order to run the backend service, I need the database to be running. I included two `docker-compose` files:
- `docker-compose.yaml` is for local  development which only has the `postgres` service
- `docker-compose.prod.yaml` has the Java service and the `postgres` db

But now that you mention it, there is no verification that the service started succesfully as I am only making sure that the code compiles. I will get rid of the `Start postgres with docker-compose` task

2024-11-21 20:25 UTC, ezrizhu commented
Could you also add this branch to the list of branches that triggers this run so we can see it working?

2024-11-22 00:51 UTC, ezrizhu commented on docker-compose.prod.yaml
should this also include the orservice docker container?

2024-11-22 00:53 UTC, ezrizhu commented on .github/workflows/docker.yaml
> +      - name: Set up JDK 17
we don't need these anymore correct?

2024-11-22 00:53 UTC, ezrizhu commented on .github/workflows/docker.yaml
> +      - name: Set up JDK 17
the java, mvn bits, everything before docker

2024-11-23 19:46 UTC, miguel-merlin commented
@ezrizhu I removed all the java related stuff (jdk and maven), the build passed for all tasks. I am going to add a new commit removing the docker task from `feature/pipeline`

2024-11-23 20:38 UTC, ezrizhu approved these changes
lg2m nice work

2024-12-04 23:38 UTC, ezrizhu commented on docker-compose.prod.yaml
Please add the rest of the services we will have on prod here, and ensure that both frontend and backend have the `"com.centurylinklabs.watchtower.scope=orservice"` label, let's not label the database with that to prevent silent db update errors. 
when adding the frontend and backend app, use the label :prod-latest, so wt to always pull the prod-latest image.

2024-12-04 23:38 UTC, ezrizhu requested changes
see comment

2024-12-12 07:34 UTC, ezrizhu approved these changes
lgtm test prod config on dev & merge

2024-12-12 16:25 UTC, merged